name: "mnist_rbm"
model_type: DBM
layer {
  name: "input_layer"
  dimensions: 784
  param {
    name: "bias"
    initialization: CONSTANT
  }
  is_input: true
  loss_function: SQUARED_LOSS
  hyperparams {
    dropout: false
  }
  data_field {
    train: "train_full_data"
    test: "test_data"
  }
  performance_stats {
    compute_error: true
  }
  shape: 28
  shape: 28
}
layer {
  name: "hidden1"
  dimensions: 1024
  param {
    name: "bias"
    initialization: CONSTANT
  }
  performance_stats {
    compute_sparsity: true
  }
  shape: 16
  shape: 16
}
edge {
  node1: "input_layer"
  node2: "hidden1"
  directed: false
  param {
    name: "weight"
    initialization: DENSE_GAUSSIAN_SQRT_FAN_IN
    sigma: 0.01
  }
  receptive_field_width: 28
  display_rows: 16
  display_cols: 16
}
hyperparams {
  base_epsilon: 0.01
  epsilon_decay: NONE
  epsilon_decay_half_life: 5000
  initial_momentum: 0.5
  final_momentum: 0.9
  momentum_change_steps: 3000
  sparsity: false
  sparsity_target: 0.1
  sparsity_cost: 0.01
  sparsity_damping: 0.9
  dropout: false
  dropout_prob: 0.5
  apply_weight_norm: false
  weight_norm: 3.0
  apply_l2_decay: true
  l2_decay: 0.001
  activation: LOGISTIC
  gibbs_steps: 1
}
